<template>
  <div class="container">
    <div class="section links">
      <Nav />
    </div>
    <div class="section details">
      <!-- CONTENT START -->
      <h1 class="title">Obituary</h1>
     <div class="a">
      <p>William Patrick Davis, of Towson, MD died peacefully at the age of 86 on April 4, 2024.  He is survived by his loving wife, Jeanne Davis (nee March); beloved children, Brian Davis, Lisa Davis (Patrick), Zachary Davis (Danielle), Liam Davis, and Timothy Davis; dear grandchildren Brian Davis (Lindsey), Sarah Davis (Aaron), and Julian Davis; and great-grandchild, Briar Davis. He is also survived by his siblings Thomas Davis (Peggy), Elizabeth Shontz (Walter), Murray Davis (Chris), James Davis, and Ellen Peppler, along with many nieces and nephews.  He was predeceased by his loving parents, William and Rita Davis.</p>
      <p>Patrick, known to many as Pat or Paddy, was originally to be named William Thomas Davis, after his father.  When he arrived on St. Patrick’s Day in 1938, however, it was decided that his middle name would instead honor the patron saint of Ireland.  He was the eldest of six children who, along with their parents, lived in what was then called the Tenth Ward in Baltimore City.  Patrick had many colorful stories of growing up in the city in the 1940’s and 50’s. He was so enamored of cowboy movies when he was little that he slept every night with a beloved toy horse, Silver, that he had been given for Christmas.  He often told his children about the wonderful summers he spent with his brother Tommy and his Uncle Stevie (who was only months older than he was) at Camp Puh’tok as a child, where he learned about Native American culture and the outdoors.  This was a treat for little boys from East Baltimore, afforded to them by their grandfather, ” Doc” Kilduff.</p>
      <p>Patrick began his schooling at what was St. Ann’s on Greenmount Avenue, and later went to The Shrine of the Little Flower School, where he loved being a member of the Drum and Bugle Corps, forming many happy memories of trips taken for performances and competitions.  He attended Calvert Hall College High School—then located on Cathedral Street in downtown Baltimore-- where he enjoyed playing sports, particularly ice hockey.  He graduated in 1956 and decided to enlist that same year in the Marine Corps, first training at MCRD Parris Island (where he would return regularly to watch the new Marines graduate), and then Camp Lejeune.  He retired from the Marine Corps Reserves as a First Sergeant in 1979. Patrick started working for Baltimore’s Daily Record as a boy serving papers, and eventually worked his way into an office position.  He later started a career with the City of Baltimore as a printer/planner in the City’s Print Shop, eventually becoming the Manager before retiring in 2001.</p>
      <p>Patrick was a lifelong fan of the Baltimore Orioles, known as much for his impassioned expressions of frustration and disappointment at what he thought was a badly played game as for his boisterous hooting and hollering when his beloved team prevailed, especially over the reviled Yankees. He loved books and movies about military history, and was extremely knowledgeable about the various wars in which the U.S. was involved. He was a listener of big band music and jazz.  Patrick enjoyed spending summer vacations at Bethany Beach, Delaware with his family, with all of the associated traditions—the challenge of packing an ever-expanding list of necessary beach stuff into and on top of the minivan, the fun but noisy drive down, and settling into the rhythm of days spent on the beach and nights out eating at Grotto’s Pizza, playing miniature golf, and strolling on the boardwalk in nearby Ocean City.  He loved everything associated with Christmas, particularly putting up the decorations.  Each year getting the tree into the house and set up became an expletive-ridden comedy of errors, bringing to mind the father in the movie The Christmas Story.  Patrick also was a lover of movies--every new Mission Impossible and James Bond movie was a family outing. Trips to Blockbuster on Friday nights yielded many family favorites; however, upon later reflection, some of these movies may not have been age appropriate for the children at the time.  </p>
      <p>Affectionately known as Pat by his friends and Paddy by his family, he was proud of his Irish heritage, having been born into a family whose ancestors emigrated to the United States and settled in Fells Point in the 1800’s. When asked who his ancestors were, he suggested that they may have been horse thieves; his family was never sure whether he was kidding or not.  His many colorful, oft-repeated quotes that were at times used to pull up short an errant son were legendary and hilarious—“(insert relevant name here)--you better get your head and ass wired together!” , as were his malaprops, such as asking when at the Fenwick Bakery for a barbarian cream rather than a Bavarian cream doughnut.  Patrick was bit of a rapscallion as well as a raconteur.  He had a twinkle in his eye, a penchant for the quick retort, and an endearing, authentic Baltimore accent.  He finally made a trip to Ireland with his family in the summer of 2022.</p>
      <p>Patrick was a very active volunteer for the Baltimore Detachment Marine Corps League, serving as its Paymaster for many years at their headquarters in old Engine House 17 on Fort Avenue in Locust Point.  He also enjoyed helping to coach baseball a few seasons for Hamilton Little League. Patrick often got together to catch up with his old Shrine of the Little Flower and Calvert Hall classmates over lunch at various spots in and around Baltimore. He was a longtime participant in AA with 41 years of sobriety and enjoyed the opportunity to mentor many who came into the program. </p>
      <p>A memorial service/celebration of life will be held on Saturday, May 25th at 1:00 PM at 1426 E. Fort Avenue, Baltimore, 21230.  Contributions in his memory may be made to St. Jude Children’s Research Hospital (details at stjude.org) and to the Marine Corps League, Baltimore Detachment 565 at 1426 E. Fort Ave., Baltimore, MD  21230.</p>
     </div>
      <!-- CONTENT END -->
    </div>
  </div>
</template>

<script>
export default {}
</script>

<style lang="scss">
</style>
